### ISSUE TITLE
salt.syndic fails to compile

### ISSUE THREAD

**Issue by roskens** [saltstack-formulas/salt-formula#138] opened 2015-05-29 15:09 UTC
<pre>
# salt-call state.sls salt.syndic test=True
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** 'salt/syndic.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/map.jinja'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/defaults.yaml'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/master.sls'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/map.jinja'
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache 'salt://salt/defaults.yaml'
local:
    Data failed to compile:
----------
    A recursive requisite was found, SLS "salt.syndic" ID "salt-syndic" ID "salt-syndic"
</pre>

**Comment by iggy** [comment] 2015-06-05 18:45
The problem is https://github.com/saltstack-formulas/salt-formula/blob/master/salt/syndic.sls#L14

I don't know really how to fix it as I'm not a syndic user.

**Comment by iggy** [comment] 2015-06-17 16:52
Fixed in #146

**Closed** 2015-06-17 16:52 UTC
