### ISSUE TITLE
salt.minion is not working centos5 

### ISSUE THREAD

**Issue by msciciel** [saltstack-formulas/salt-formula#163] opened 2015-07-29 13:22 UTC
```
2015-07-29 15:09:16,376 [salt.state                                 ][ERROR   ][8517] #### /etc/salt/minion.d/f_defaults.conf ####
Unable to manage file: Jinja syntax error: no test named 'mapping'
/var/cache/salt/minion/files/itg/salt/formulas.jinja(14):
---
[...]

{%- macro formulas_git_opt(env, opt) -%}
{%- set value = salt['pillar.get']('salt_formulas:git_opts:{0}:{1}'.format(env, opt),
     salt['pillar.get']('salt_formulas:git_opts:default:{0}'.format(opt),
       defaults[opt])) -%}
{%- if value is mapping -%}    <======================
{{ value|yaml }}
{%- else -%}
{{ value }}
{%- endif -%}
{%- endmacro -%}
[...]
```

Mapping test is available from jinja version >= 2.6. But for centos5 available is only 2.5 version.

**Comment by iggy** [comment] 2015-07-29 23:11
Dupe of #93

**Closed by iggy** 2015-07-29 23:11 UTC

**Comment by gravyboat** [comment] 2015-07-30 01:32
@msciciel If you are unable to update to Jinja 2.6 feel free to fork the formula and modify it as you need to make it work with Jinja 2.5!
