### ISSUE TITLE
Installation is broken on vanilla Debian 9 (2016.11)

### ISSUE THREAD

**Issue by gboddin** [saltstack-formulas/salt-formula#407] opened 2019-04-02 12:20 UTC
Since the fix of https://github.com/saltstack-formulas/salt-formula/issues/364 a new issue has been introduced which makes it impossible to use this recipe on vanilla Debian.

`osfamilymap.yaml` has been modified with `salt['pillar.filter_by']` :
https://github.com/saltstack-formulas/salt-formula/blob/683f45579de5801db0b4aa3b701d7cadf974eb19/salt/osfamilymap.yaml#L6 

`salt['pillar.filter_by']` doesn't seems to be available on the distro provided version ( 2016.11.2 ).

Result is : 

```
dotnetcore002:
    - Rendering SLS 'base:salt.pkgrepo.debian' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'pillar.filter_by'
      /var/cache/salt/minion/files/base/salt/osfamilymap.yaml(6):
      ---
      # -*- coding: utf-8 -*-
      # vim: ft=yaml
      
      {% import_yaml "salt/ospyvermap.yaml" as ospyvermap %}
      {% set ospyver = salt['grains.filter_by'](ospyvermap, grain='os_family') or {} %}
      {% set py_ver_dir = salt['pillar.filter_by'](ospyver, pillar='salt:py_ver', default='py2') %}    <======================
      
      {% set osrelease = salt['grains.get']('osrelease') %}
      {% set salt_release = salt['pillar.get']('salt:release', 'latest') %}
      {% if salt_release.split('.')|length >= 3 %}
      {% set salt_release = 'archive/' ~ salt_release %}
      [...]
      ---
```

**Comment by myii** [comment] 2019-04-02 14:46
@gboddin Apologies for this regression, this is a duplicate of #405.  This isn't specific to Debian 9 but rather `2016.11` as you pointed out.  The thing is, `2016.11` is no longer supported, with the release of `2019.2`.  The full explanation is in #405, particularly [this comment](https://github.com/saltstack-formulas/salt-formula/issues/405#issuecomment-476723926).  There is also [a workaround](https://github.com/saltstack-formulas/salt-formula/issues/405#issuecomment-476569784) there if you need to continue supporting `2016.11` minions.

**Closed** 2019-04-03 08:38 UTC
